Acme\FooterBundle\Entity\Followus:
    type: entity
    table: null
    repositoryClass: Acme\FooterBundle\Entity\FollowusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        logo:
            type: string
            length: 255
        link:
            type: string
            length: 255
        status:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
