parameters:
#    acme_footer.example.class: Acme\FooterBundle\Example

services:
#    acme_footer.example:
#        class: %acme_footer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
