Acme\InfoBundle\Entity\Front:
    type: entity
    table: null
    repositoryClass: Acme\InfoBundle\Entity\FrontRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
