parameters:
#    acme_info.example.class: Acme\InfoBundle\Example

services:
#    acme_info.example:
#        class: %acme_info.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
